-- Generated by scripts/generate-neovim-themes.mjs. Do not edit by hand.

return {
  name = "Dark Rock",
  slug = "dark-rock",
  background = "dark",
  colors = {
    bg = "#121518",
    bgAlt = "#181b20",
    bgPanel = "#121518",
    bgStatus = "#121518",
    bgVisual = "#3d3937",
    bgSearch = "#3d2c22",
    bgSearchCurrent = "#313627",
    bgLine = "#272727",
    bgFold = "#2c2b2b",
    bgDiffAdd = "#2a352d",
    bgDiffDelete = "#3c2526",
    bgDiffChange = "#283535",
    bgDiffText = "#2a352d",
    fg = "#d4be98",
    fgAlt = "#a89984",
    fgMuted = "#928374",
    fgInactive = "#7c6f64",
    border = "#7c6f64",
    borderMuted = "#45403d",
    cursor = "#d4be98",
    lineNumber = "#7d7d7d",
    lineNumberActive = "#928374",
    whitespace = "#45403d",
    red = "#ea6962",
    orange = "#e78a4e",
    yellow = "#d8a657",
    green = "#a9b665",
    aqua = "#89b482",
    blue = "#7daea3",
    purple = "#d3869b",
  },
  syntax = {
    keyword = {
      fg = "#ea6962",
    },
    storage = {
      fg = "#e78a4e",
    },
    operator = {
      fg = "#e78a4e",
    },
    string = {
      fg = "#d8a657",
    },
    stringEscape = {
      fg = "#a9b665",
    },
    functionName = {
      fg = "#a9b665",
    },
    preproc = {
      fg = "#89b482",
    },
    module = {
      fg = "#89b482",
    },
    type = {
      fg = "#7daea3",
    },
    className = {
      fg = "#7daea3",
    },
    number = {
      fg = "#d3869b",
    },
    boolean = {
      fg = "#d3869b",
    },
    constant = {
      fg = "#d3869b",
    },
    variable = {
      fg = "#d4be98",
    },
    property = {
      fg = "#d4be98",
    },
    punctuation = {
      fg = "#d4be98",
    },
    tag = {
      fg = "#e78a4e",
    },
    attribute = {
      fg = "#d8a657",
    },
    comment = {
      fg = "#928374",
      italic = true,
    },
    markdownHeading1 = {
      fg = "#ea6962",
      bold = true,
    },
    markdownHeading2 = {
      fg = "#e78a4e",
      bold = true,
    },
    markdownHeading3 = {
      fg = "#d8a657",
      bold = true,
    },
    markdownHeading4 = {
      fg = "#a9b665",
      bold = true,
    },
    markdownHeading5 = {
      fg = "#7daea3",
      bold = true,
    },
    markdownHeading6 = {
      fg = "#d3869b",
      bold = true,
    },
    markdownLink = {
      fg = "#a9b665",
      underline = true,
    },
    markdownCode = {
      fg = "#a9b665",
    },
    diffDelete = {
      fg = "#ea6962",
    },
    diffAdd = {
      fg = "#a9b665",
    },
    diffChange = {
      fg = "#7daea3",
    },
  },
}
