-- Generated by scripts/generate-neovim-themes.mjs. Do not edit by hand.

return {
  name = "Light Rock",
  slug = "light-rock",
  background = "light",
  colors = {
    bg = "#e5e1dc",
    bgAlt = "#e5e1dc",
    bgPanel = "#d5d0c9",
    bgStatus = "#d5d0c9",
    bgVisual = "#c4beb6",
    bgSearch = "#c9b7a5",
    bgSearchCurrent = "#c3c7c9",
    bgLine = "#d5d0c9",
    bgFold = "#d8d3cd",
    bgDiffAdd = "#cbcece",
    bgDiffDelete = "#d7b7b4",
    bgDiffChange = "#adc2c3",
    bgDiffText = "#c3c7c9",
    fg = "#3d3a36",
    fgAlt = "#4a4741",
    fgMuted = "#706b63",
    fgInactive = "#706b63",
    border = "#b5aea5",
    borderMuted = "#b5aea5",
    cursor = "#3d3a36",
    lineNumber = "#9b958d",
    lineNumberActive = "#4a4741",
    whitespace = "#b5aea5",
    red = "#9d0006",
    orange = "#8b5c42",
    yellow = "#8b5a2d",
    green = "#5c7a92",
    aqua = "#427b58",
    blue = "#076678",
    purple = "#8f3f71",
  },
  syntax = {
    keyword = {
      fg = "#9d0006",
    },
    storage = {
      fg = "#8b5c42",
    },
    operator = {
      fg = "#8b5c42",
    },
    string = {
      fg = "#8b5a2d",
    },
    stringEscape = {
      fg = "#5c7a92",
    },
    functionName = {
      fg = "#5c7a92",
    },
    preproc = {
      fg = "#427b58",
    },
    module = {
      fg = "#427b58",
    },
    type = {
      fg = "#076678",
    },
    className = {
      fg = "#076678",
    },
    number = {
      fg = "#8f3f71",
    },
    boolean = {
      fg = "#8f3f71",
    },
    constant = {
      fg = "#8f3f71",
    },
    variable = {
      fg = "#3d3a36",
    },
    property = {
      fg = "#3d3a36",
    },
    punctuation = {
      fg = "#3d3a36",
    },
    tag = {
      fg = "#8b5c42",
    },
    attribute = {
      fg = "#8b5a2d",
    },
    comment = {
      fg = "#706b63",
      italic = true,
    },
    markdownHeading1 = {
      fg = "#9d0006",
      bold = true,
    },
    markdownHeading2 = {
      fg = "#8b5c42",
      bold = true,
    },
    markdownHeading3 = {
      fg = "#8b5a2d",
      bold = true,
    },
    markdownHeading4 = {
      fg = "#5c7a92",
      bold = true,
    },
    markdownHeading5 = {
      fg = "#076678",
      bold = true,
    },
    markdownHeading6 = {
      fg = "#8f3f71",
      bold = true,
    },
    markdownLink = {
      fg = "#5c7a92",
      underline = true,
    },
    markdownCode = {
      fg = "#5c7a92",
    },
    diffDelete = {
      fg = "#9d0006",
    },
    diffAdd = {
      fg = "#5c7a92",
    },
    diffChange = {
      fg = "#076678",
    },
  },
}
