-- Generated by scripts/generate-neovim-themes.mjs. Do not edit by hand.

local M = {}

local default_options = {
  transparent = vim.g.dark_rock_transparent == true or vim.g.dark_rock_transparent == 1,
  nvim_tree_folder_color = vim.g.dark_rock_nvim_tree_folder_color or "fgAlt",
}

M.options = vim.deepcopy(default_options)

local function apply_highlights(groups)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

local function normalize_setup_args(theme_name, options)
  if type(theme_name) == "table" then
    return theme_name.theme or theme_name.name or "dark-rock", theme_name
  end

  return theme_name or "dark-rock", options or {}
end

function M.configure(options)
  M.options = vim.tbl_deep_extend("force", M.options, options or {})
end

function M.setup(theme_name, options)
  local selected_theme_name, setup_options = normalize_setup_args(theme_name, options)
  local ok, palette = pcall(require, "dark-rock.palettes." .. selected_theme_name)

  if not ok then
    error(("dark-rock theme %q not found"):format(selected_theme_name))
  end

  M.configure(setup_options)

  vim.o.termguicolors = true
  vim.o.background = palette.background

  vim.cmd("highlight clear")

  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.g.colors_name = selected_theme_name

  apply_highlights(require("dark-rock.highlights").get(palette, M.options))
end

return M
